services:

  nginx:
    image: nginx:latest

    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      api:
        condition: service_healthy


  api:
    image: satyamshrestha/talentforge:latest

    restart: unless-stopped

    expose:
      - "8000"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}

      UPLOAD_DIR: ${UPLOAD_DIR}

      LLM_PROVIDER: ${LLM_PROVIDER}
      LLM_MODEL: ${LLM_MODEL}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      OLLAMA_TIMEOUT: ${OLLAMA_TIMEOUT}
      OLLAMA_RETRIES: ${OLLAMA_RETRIES}

    volumes:
      - resume_uploads:/app/uploads/resumes

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/health')"
        ]
      interval: 30s
      timeout: 10s
      retries: 3


  celery_worker:
    image: satyamshrestha/talentforge:latest

    restart: unless-stopped

    command: celery -A tasks.celery_app.celery worker --loglevel=info

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}

      UPLOAD_DIR: ${UPLOAD_DIR}

      LLM_PROVIDER: ${LLM_PROVIDER}
      LLM_MODEL: ${LLM_MODEL}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      OLLAMA_TIMEOUT: ${OLLAMA_TIMEOUT}
      OLLAMA_RETRIES: ${OLLAMA_RETRIES}

    volumes:
      - resume_uploads:/app/uploads/resumes


  db:
    image: postgres:17

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:8.2

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
  resume_uploads: