"""add suggested improvement to answers and change score data type to int from str

Revision ID: 703408acaf27
Revises: 39cca3d451d1
Create Date: 2026-07-23 09:49:43.473505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703408acaf27'
down_revision: Union[str, Sequence[str], None] = '39cca3d451d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('suggested_improvement', sa.String(), nullable=True))
    op.alter_column(
        'answers',
        'score',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="score::integer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'answers',
        'score',
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
        postgresql_using="score::varchar"
    )
    op.drop_column('answers', 'suggested_improvement')
    # ### end Alembic commands ###
