"""add provider in user

Revision ID: c29450677b61
Revises: f4e2a4377d11
Create Date: 2026-06-30 09:56:53.690166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29450677b61'
down_revision: Union[str, Sequence[str], None] = 'f4e2a4377d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'users',
        sa.Column(
            'provider',
            sa.String(),
            nullable=False,
            server_default='local'
        )
    )

    op.alter_column(
        'users',
        'provider',
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
