"""add role to users

Revision ID: f4e2a4377d11
Revises: 626e2fd9eda7
Create Date: 2026-06-25 09:50:52.244774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e2a4377d11'
down_revision: Union[str, Sequence[str], None] = '626e2fd9eda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.String(),
            nullable=False,
            server_default="student"
        )
    )

    op.alter_column(
        "users",
        "role",
        server_default=None
    )
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
