from enum import Enum


class WebSocketEvent(str, Enum):
    INTERVIEW_STARTED = "INTERVIEW_STARTED"
    QUESTION_AVAILABLE = "QUESTION_AVAILABLE"
    ANSWER_SUBMITTED = "ANSWER_SUBMITTED"
    ANSWER_EVALUATED = "ANSWER_EVALUATED"
    INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED"